version: '3.8'

services:

  bookingProcess:
    build: ./bookingProcess
    image: cargoverload/booking-process
    restart: unless-stopped
    container_name: bookingProcess
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cargoverload
    depends_on:
      - mongo
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - services
      - proxy

  carAvailability:
    build: ./carAvailability
    image: cargoverload/car-availability
    restart: unless-stopped
    container_name: carAvailability
    environment:
      - PORT=3001
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cargoverload
    depends_on:
      - mongo
    expose:
      - "3001"
    ports:
      - 3001:3001
    networks:
      - services
      - proxy

  carBooking:
    build: ./carBooking
    image: cargoverload/car-booking
    restart: unless-stopped
    container_name: carBooking
    environment:
      - PORT=3002
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cargoverload
    depends_on:
      - mongo
    expose:
      - "3002"
    ports:
      - 3002:3002
    networks:
      - services
      - proxy

  carSearching:
    build: ./carSearching
    image: cargoverload/car-searching
    restart: unless-stopped
    container_name: carSearching
    environment:
      - PORT=3003
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cargoverload
    depends_on:
      - mongo
    expose:
      - "3003"
    ports:
      - 3003:3003
    networks:
      - services
      - proxy


  mongo:
    image: mongo:latest
    container_name: cargoverload-mongo
    restart: unless-stopped
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: toor
      - MONGODB_DATABASE="cargoverload"
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - services

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./reverse_proxy.conf:/etc/nginx/nginx.conf
#    networks:
#      - proxy
#    ports:
#      - 80:80

networks:
  services:
  proxy:

